const CHANNELS=[{handle:'SimGamerJen',label:'SimGamerJen'},{handle:'StreamGamerJen',label:'StreamGamerJen'}];
const YOUTUBE_HEADERS={'User-Agent':'Mozilla/5.0 (compatible; SimGamerJenWebsite/1.0; +https://simgamerjen.com)','Accept-Language':'en-GB,en;q=0.9'};
function decodeXml(v=''){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)));}
function textTag(xml,tag){const m=xml.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decodeXml(m[1].trim()):'';}
function stripMarkup(v=''){return decodeXml(v.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function decodeJsonText(v=''){try{return JSON.parse(`"${v.replace(/"/g,'\\"')}"`);}catch{return v.replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/\\n/g,' ');}}
function htmlEntityDecode(v=''){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function metaContent(html,property){const esc=property.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=html.match(new RegExp(`<meta[^>]+property=["']${esc}["'][^>]+content=["']([^"']+)["']`,'i'));const b=html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+property=["']${esc}["']`,'i'));return htmlEntityDecode((a||b||[])[1]||'');}
async function resolveChannelId(handle){const r=await fetch(`https://www.youtube.com/@${encodeURIComponent(handle)}`,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:21600}});if(!r.ok)throw new Error(`channel-page-${r.status}`);const html=await r.text();const rss=(html.match(/"rssUrl":"https:\/\/www\.youtube\.com\/feeds\/videos\.xml\?channel_id=(UC[\w-]{20,})"/)||[])[1];if(rss)return rss;const metadata=(html.match(/"channelMetadataRenderer":\{[\s\S]{0,8000}?"externalId":"(UC[\w-]{20,})"/)||[])[1];if(metadata)return metadata;const itemprop=(html.match(/itemprop="channelId"\s+content="(UC[\w-]{20,})"/)||html.match(/content="(UC[\w-]{20,})"\s+itemprop="channelId"/)||[])[1];if(itemprop)return itemprop;throw new Error(`channel-id-not-found-${handle}`);}
function parseFeed(xml,channel){const entries=xml.match(/<entry>[\s\S]*?<\/entry>/gi)||[];return entries.map(entry=>{const id=textTag(entry,'yt:videoId'),title=textTag(entry,'title'),published=textTag(entry,'published'),description=stripMarkup(textTag(entry,'media:description')).slice(0,220);if(!id||!title||!published)return null;return{id,title,published,description,channel:channel.label,handle:channel.handle,url:`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`,thumbnail:`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`};}).filter(Boolean);}
async function fetchChannelItems(channel){const channelId=await resolveChannelId(channel.handle);const r=await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(channelId)}`,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:900}});if(!r.ok)throw new Error(`feed-${channel.handle}-${r.status}`);return parseFeed(await r.text(),channel);}
function findTitle(segment=''){for(const p of [/"title":\{"content":"((?:\\.|[^"\\])*)"/i,/"title":\{"simpleText":"((?:\\.|[^"\\])*)"/i,/"title":\{"runs":\[\{"text":"((?:\\.|[^"\\])*)"/i]){const m=segment.match(p);if(m)return decodeJsonText(m[1]);}return'';}
function discoverPlaylists(html,channel){const found=new Map();const add=(id,index)=>{if(!id||found.has(id))return;const start=Math.max(0,index-1800),end=Math.min(html.length,index+4200),segment=html.slice(start,end);const title=findTitle(segment);if(!title||/^(play all|view full playlist)$/i.test(title))return;found.set(id,{id,title,channel:channel.label,handle:channel.handle,url:`https://www.youtube.com/playlist?list=${encodeURIComponent(id)}`,thumbnail:''});};for(const re of [/"contentId":"(PL[\w-]+)"/g,/"playlistId":"(PL[\w-]+)"/g]){let m;while((m=re.exec(html))!==null)add(m[1],m.index);}return[...found.values()].slice(0,20);}
function firstPlaylistVideoId(html=''){const patterns=[/"playlistVideoRenderer":\{[\s\S]{0,2400}?"videoId":"([\w-]{6,})"/,/"playlistPanelVideoRenderer":\{[\s\S]{0,2400}?"videoId":"([\w-]{6,})"/];for(const pattern of patterns){const m=html.match(pattern);if(m)return m[1];}return'';}
async function playlistPageMetadata(id,hint={}){const url=`https://www.youtube.com/playlist?list=${encodeURIComponent(id)}`;try{const r=await fetch(url,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:21600}});if(!r.ok)return hint.title?{...hint,id,url}:null;const html=await r.text();const title=metaContent(html,'og:title')||hint.title||'';const videoId=firstPlaylistVideoId(html);const thumbnail=videoId?`https://i.ytimg.com/vi/${encodeURIComponent(videoId)}/hqdefault.jpg`:'';const owner=(html.match(/"ownerText":\{"runs":\[\{"text":"((?:\\.|[^"\\])*)"/)||html.match(/"shortBylineText":\{"runs":\[\{"text":"((?:\\.|[^"\\])*)"/)||[])[1];const channel=owner?decodeJsonText(owner):(hint.channel||'YouTube');if(!title)return null;return{id,title,channel,handle:hint.handle||'',url,thumbnail};}catch{return hint.title?{...hint,id,url}:null;}}
async function fetchChannelPlaylists(channel){const r=await fetch(`https://www.youtube.com/@${encodeURIComponent(channel.handle)}/playlists`,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:1800}});if(!r.ok)throw new Error(`playlists-${channel.handle}-${r.status}`);const discovered=discoverPlaylists(await r.text(),channel);const resolved=await Promise.all(discovered.map(item=>playlistPageMetadata(item.id,item)));return resolved.filter(Boolean);}
async function allDiscoveredPlaylists(){const settled=await Promise.allSettled(CHANNELS.map(fetchChannelPlaylists));return settled.filter(x=>x.status==='fulfilled').flatMap(x=>x.value);}
async function curatedPlaylists(ids){const resolved=await Promise.all(ids.map(id=>playlistPageMetadata(id)));return resolved.filter(Boolean);}
async function cachedJson(request,ctx,path,producer,ttl=900){const cache=caches.default,key=new Request(new URL(path,request.url),{method:'GET'}),cached=await cache.match(key);if(cached)return cached;const data=await producer();const response=Response.json(data,{headers:{'Cache-Control':`public, max-age=300, s-maxage=${ttl}`,'X-Content-Type-Options':'nosniff'}});ctx.waitUntil(cache.put(key,response.clone()));return response;}
async function latestYouTube(request,ctx){return cachedJson(request,ctx,'/api/youtube/latest-v2',async()=>{const settled=await Promise.allSettled(CHANNELS.map(fetchChannelItems));const items=settled.filter(x=>x.status==='fulfilled').flatMap(x=>x.value).sort((a,b)=>new Date(b.published)-new Date(a.published)).slice(0,3);if(!items.length)throw new Error('youtube-feed-unavailable');return{generatedAt:new Date().toISOString(),channels:CHANNELS.map(c=>c.handle),items};});}
async function youtubePlaylists(request,ctx){const requestUrl=new URL(request.url);const raw=requestUrl.searchParams.get('ids')||'';const ids=[...new Set(raw.split(',').map(v=>v.trim()).filter(v=>/^PL[\w-]+$/.test(v)))].slice(0,6);const cachePath=ids.length?`/api/youtube/playlists-curated-v2?ids=${ids.join(',')}`:'/api/youtube/playlists-v5';return cachedJson(request,ctx,cachePath,async()=>{const items=ids.length?await curatedPlaylists(ids):await allDiscoveredPlaylists();if(!items.length)throw new Error('youtube-playlists-unavailable');return{generatedAt:new Date().toISOString(),channels:CHANNELS.map(c=>c.handle),curated:Boolean(ids.length),items};},21600);}
export default{async fetch(request,env,ctx){const url=new URL(request.url);try{if(request.method==='GET'&&url.pathname==='/api/youtube/latest')return await latestYouTube(request,ctx);if(request.method==='GET'&&url.pathname==='/api/youtube/playlists')return await youtubePlaylists(request,ctx);}catch(error){return Response.json({error:String(error?.message||error)},{status:503,headers:{'Cache-Control':'no-store'}});}return env.ASSETS.fetch(request);}};