const CHANNELS=[{handle:'SimGamerJen',label:'SimGamerJen'},{handle:'StreamGamerJen',label:'StreamGamerJen'}];
const YOUTUBE_HEADERS={'User-Agent':'Mozilla/5.0 (compatible; SimGamerJenWebsite/1.0; +https://simgamerjen.com)','Accept-Language':'en-GB,en;q=0.9'};
function decodeXml(v=''){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)));}
function textTag(xml,tag){const m=xml.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decodeXml(m[1].trim()):'';}
function stripMarkup(v=''){return decodeXml(v.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function decodeJsonText(v=''){try{return JSON.parse(`"${v.replace(/"/g,'\\"')}"`);}catch{return v.replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/\\n/g,' ');}}
async function resolveChannelId(handle){const r=await fetch(`https://www.youtube.com/@${encodeURIComponent(handle)}`,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:21600}});if(!r.ok)throw new Error(`channel-page-${r.status}`);const html=await r.text();for(const p of [/"channelId":"(UC[\w-]{20,})"/,/"externalId":"(UC[\w-]{20,})"/,/itemprop="channelId"\s+content="(UC[\w-]{20,})"/,/content="(UC[\w-]{20,})"\s+itemprop="channelId"/]){const m=html.match(p);if(m)return m[1];}throw new Error(`channel-id-not-found-${handle}`);}
function parseFeed(xml,channel){const entries=xml.match(/<entry>[\s\S]*?<\/entry>/gi)||[];return entries.map(entry=>{const id=textTag(entry,'yt:videoId'),title=textTag(entry,'title'),published=textTag(entry,'published'),description=stripMarkup(textTag(entry,'media:description')).slice(0,220);if(!id||!title||!published)return null;return{id,title,published,description,channel:channel.label,handle:channel.handle,url:`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`,thumbnail:`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`};}).filter(Boolean);}
async function fetchChannelItems(channel){const channelId=await resolveChannelId(channel.handle);const r=await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${encodeURIComponent(channelId)}`,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:900}});if(!r.ok)throw new Error(`feed-${channel.handle}-${r.status}`);return parseFeed(await r.text(),channel);}
function findTitle(segment=''){for(const p of [/"title":\{"content":"((?:\\.|[^"\\])*)"/i,/"title":\{"simpleText":"((?:\\.|[^"\\])*)"/i,/"title":\{"runs":\[\{"text":"((?:\\.|[^"\\])*)"/i]){const m=segment.match(p);if(m)return decodeJsonText(m[1]);}return'';}
function discoverPlaylists(html,channel){const found=new Map();const add=(id,index)=>{if(!id||found.has(id))return;const start=Math.max(0,index-1800),end=Math.min(html.length,index+4200),segment=html.slice(start,end);const title=findTitle(segment);if(!title||/^(play all|view full playlist)$/i.test(title))return;found.set(id,{id,title,channel:channel.label,handle:channel.handle,url:`https://www.youtube.com/playlist?list=${encodeURIComponent(id)}`,thumbnail:''});};for(const re of [/"contentId":"(PL[\w-]+)"/g,/"playlistId":"(PL[\w-]+)"/g]){let m;while((m=re.exec(html))!==null)add(m[1],m.index);}return[...found.values()].slice(0,12);}
function htmlEntityDecode(v=''){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
async function playlistThumbnail(item){try{const r=await fetch(item.url,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:1800}});if(!r.ok)return item;const html=await r.text();const image=(html.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i)||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i)||[])[1]||'';return{...item,thumbnail:htmlEntityDecode(image)};}catch{return item;}}
async function fetchChannelPlaylists(channel){const r=await fetch(`https://www.youtube.com/@${encodeURIComponent(channel.handle)}/playlists`,{headers:YOUTUBE_HEADERS,cf:{cacheEverything:true,cacheTtl:1800}});if(!r.ok)throw new Error(`playlists-${channel.handle}-${r.status}`);const discovered=discoverPlaylists(await r.text(),channel);return Promise.all(discovered.map(playlistThumbnail));}
async function cachedJson(request,ctx,path,producer,ttl=900){const cache=caches.default,key=new Request(new URL(path,request.url),{method:'GET'}),cached=await cache.match(key);if(cached)return cached;const data=await producer();const response=Response.json(data,{headers:{'Cache-Control':`public, max-age=300, s-maxage=${ttl}`,'X-Content-Type-Options':'nosniff'}});ctx.waitUntil(cache.put(key,response.clone()));return response;}
async function latestYouTube(request,ctx){return cachedJson(request,ctx,'/api/youtube/latest',async()=>{const settled=await Promise.allSettled(CHANNELS.map(fetchChannelItems));const items=settled.filter(x=>x.status==='fulfilled').flatMap(x=>x.value).sort((a,b)=>new Date(b.published)-new Date(a.published)).slice(0,3);if(!items.length)throw new Error('youtube-feed-unavailable');return{generatedAt:new Date().toISOString(),channels:CHANNELS.map(c=>c.handle),items};});}
async function youtubePlaylists(request,ctx){return cachedJson(request,ctx,'/api/youtube/playlists-v3',async()=>{const settled=await Promise.allSettled(CHANNELS.map(fetchChannelPlaylists));const items=settled.filter(x=>x.status==='fulfilled').flatMap(x=>x.value);if(!items.length)throw new Error('youtube-playlists-unavailable');return{generatedAt:new Date().toISOString(),channels:CHANNELS.map(c=>c.handle),items};},1800);}
export default{async fetch(request,env,ctx){const url=new URL(request.url);try{if(request.method==='GET'&&url.pathname==='/api/youtube/latest')return await latestYouTube(request,ctx);if(request.method==='GET'&&url.pathname==='/api/youtube/playlists')return await youtubePlaylists(request,ctx);}catch(error){return Response.json({error:String(error?.message||error)},{status:503,headers:{'Cache-Control':'no-store'}});}return env.ASSETS.fetch(request);}};